### PR TITLE
add liferay-gradle-build-lang-plugin required parameters

### PR DESCRIPTION
**Pull request by gamerson**

### CODE REVIEW

**Comment by gamerson** [comment]
@lovettli can you add these to gradle.properties instead?

**Comment by Ithildir** [comment]
Hi! We should probably keep these properties empty in gradle.properties, just like we have in [build.properties](https://github.com/liferay/liferay-portal/blob/master/build.properties#L150).

**Comment by lovettli** [comment]
@Ithildir Probably we need provide some commands like build-lang for liferay workspace. So you mean we just set following code in gradle.properties , 
```
microsoft.translator.client.id=
microsoft.translator.client.secret=
```
then liferay gradle build lang plugin can set these value into  "translateClientId" and "translateClientSecret" properties of BuildLangTask . right?

**Comment by Ithildir** [comment]
Yes :blush: Technically, it's done by `LiferayDefaultsPlugin`, which is automatically applied by `LiferayJavaPlugin`: https://github.com/liferay/liferay-portal/blob/master/modules/sdk/gradle-plugins/src/main/java/com/liferay/gradle/plugins/LangBuilderDefaultsPlugin.java#L40

**Comment by lovettli** [comment]
OK. got it. Thank you.

**Pull request closed without merging**
